-file("/usr/local/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(els_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 61).

-include_lib("els_scan.hrl").
-include_lib("els.hrl").
%%-export([tokenizer/2]).
-export([file/2]).
%%-export([read_balance/4]).
%%-export([read/3]).
%%-export([read/6]).
-export([reads/5]).
-export([from_string/2]).
-export([from_string/1]).
%%-export([replace/5]).
-export([read/5]).
-export([replace/5]).
-export([remove_nl/1]).

  
calclevel(IO, Prompt0, Tokens, GLevel, Line) ->
%%    io:format("calclevel [~p]~n", [Tokens]),
    R=do_calclevel(IO, Prompt0, Tokens, {[], GLevel}, Line),
%%    io:format("calclevelout [~p]~n", [R]),
    R.

do_calclevel(_IO, _Prompt0, [], {Acc, PreLevel}, Line) ->
%%    io:format("calc-out ): ~p ~p ~n", [PreLevel, Acc]),
    {Acc, PreLevel, [], Line};
do_calclevel(IO, Prompt0, [{'(', _Loc} =T | Tokens], {Acc, PreLevel}, Line) ->
    do_calclevel(IO, Prompt0, Tokens, {Acc ++ [T], PreLevel+1}, Line);
do_calclevel(_IO, _Prompt0, [{')', _Loc} =T | Tokens], {Acc, PrevLevel}, Line) when PrevLevel =< 1 ->
    {Acc ++ [T], PrevLevel-1, Tokens, Line};
do_calclevel(IO, Prompt0, [{')', _Loc} =T | Tokens], {Acc, PreLevel}, Line) ->
%%    io:format("calc-apply ): ~p ~p ~p ~n", [PreLevel, Acc, Tokens]),
    do_calclevel(IO, Prompt0, Tokens, {Acc ++ [T], PreLevel-1}, Line);
do_calclevel(IO, Prompt0, [{read_macro, Loc, MChar}], {Acc, PreLevel}, _Line) ->
    RM = #{quote => {?MODULE, replace},
           backquote => {?MODULE, replace},
           unquote => {?MODULE, replace},
           unquote_splice => {?MODULE, replace}
          },
    {MM, MF} = maps:get(MChar, RM, {?MODULE, not_implemented}),
    %io:format("calc-apply before: ~p ~p ~n", [Loc, Acc]),
    {ok, NewTokens, NewLoc, RestTokens} = apply(MM, MF, [{IO, Prompt0}, ?MODULE, read, 
                                                         Loc, MChar]),
    %io:format("calc-apply after: NT ~p Rest ~p PL ~p ~n", [NewTokens, RestTokens, PreLevel]),
    do_calclevel(IO, Prompt0, RestTokens, {Acc ++ NewTokens, PreLevel}, NewLoc);
do_calclevel(IO, Prompt0, [{'\n', _Loc} | Tokens], {Acc, PreLevel}, Line) ->
    do_calclevel(IO, Prompt0, Tokens, {Acc, PreLevel}, Line);
do_calclevel(_IO, _Prompt0, [T | Tokens], {Acc, 0}, Line) ->
    {Acc++[T], 0, Tokens, Line};
do_calclevel(IO, Prompt0, [T | Tokens], {Acc, PreLevel}, Line) ->
    do_calclevel(IO, Prompt0, Tokens, {Acc ++ [T], PreLevel}, Line).
loctoline({Line, _Col}) ->
    Line;
loctoline(Line) ->
    Line.
    
replace({IO, _Prompt0}, _M, _F, Loc, MChar) ->
    %Ret = read(IO, Prompt0, loctoline(Loc), [], 0),
    Ret = read(IO, "", loctoline(Loc), [], 0),
    %io:format("replace-2read ~p~n", [Ret]),
    {ok, Tokens, NextLine, Rest} = Ret,
    {_L, ACol} = Loc,
    N2Tokens = lists:map(fun({T, {L, C}, V}) ->
                                 {T, {L, C+ACol}, V};
                            ({T, {L, C}}) ->
                                 {T, {L, C+ACol}};
                            (T) ->
                                 T
                         end, Tokens),
    N2Rest = lists:map(fun({T, {L, C}, V}) ->
                                 {T, {L, C+ACol}, V};
                          ({T, {L, C}}) ->
                                 {T, {L, C+ACol}};
                          (T) ->
                               T
                         end, Rest),
    NewTokens = [{'(', Loc}, 
                 {symbol, Loc, atom_to_list(MChar)} | 
                 N2Tokens ++ [{')', Loc}]],
    {ok, NewTokens, NextLine, N2Rest}.

make_prompt([], _Line, _PrevTokens) ->
    "";
make_prompt(Prompt, Line, []) ->
    io_lib:format(Prompt, [loctoline(Line)]);
make_prompt(_Prompt, _Line, _PrevTokens) ->
    "".

adjust_level(IO, Prompt0, PrevTokens, PrevLevel, Line) ->
    {NNewTokens, NLevel, Rest, NewLine} = calclevel(IO, Prompt0, PrevTokens, PrevLevel, Line),
    Tokens = NNewTokens,
    case {Rest, NLevel} of
        {[], NLevel} when NLevel > 0 -> 
            %io:format("Readmore ~p ~p~n", [NLevel, Rest]),
            read(IO, Prompt0, NewLine, Tokens++Rest, NLevel);
        {Rest, 0} ->
            %io:format("Token ~p Rest ~p~n", [Tokens, Rest]),
            ?LOG_DEBUG(#{ajust_level => [Tokens, Rest]}),
            {ok, Tokens, NewLine, Rest};
        _  ->
            io:format("readRet ~p~n", [{ok, Tokens, NewLine, Rest}]),
            {ok, Tokens, NewLine, Rest} 
    end.

read_multiline(IO, Line, Add, Stop) ->
    case io:get_line(IO, "") of
        {error, Error} ->
            {error, Error};
        eof ->
            eof;
        Stop ->
            {Add, Line+1};
        Data ->
            io:format("GetLine ~p vi ~p ~p~n", [Stop, Data, Stop=:=Data]),
            read_multiline(IO, Line+1, string:concat(Add ,Data), Stop)
    end.

multiline_quote(IO, Line, Tokens) ->
    case lists:last(Tokens) of
        {'"""', _} ->
            {MT, L} = read_multiline(IO, Line, "",
                                     "\"\"\"\n"),
            MM = {lists:append(lists:droplast(Tokens),
                               [{string, Line, MT}]),
                  L},
            io:format("REST: ~p n ~p~n", [Tokens,MM]),
            MM;
        _ ->
            {Tokens, Line}
    end.
    
            

read(IO, Prompt0, Line, PrevTokens, PrevLevel) when length(PrevTokens) > 0 andalso PrevLevel == 0 ->
    io:format("CalcLevel PreVTokens  ~p ~n PrevLevel ~p~n", [PrevTokens, PrevLevel]),
    adjust_level(IO, Prompt0, PrevTokens, PrevLevel, Line);
read(IO, Prompt0, Line, PrevTokens, PrevLevel) ->
    Prompt = make_prompt(Prompt0, Line, PrevTokens),
    case io:request(IO, {get_until, unicode, Prompt, ?MODULE, tokens, [Line]}) of
        {ok, NewTokens, NextLine} ->
            ?LOG_DEBUG(#{prevlevel => PrevLevel,
                         prevtokens => PrevTokens,
                         newtokens => NewTokens}),
            {NewTokens2, NextLine2} =  multiline_quote(IO, NextLine, NewTokens),
            %%?LOG_DEBUG(#{adjust_level => PrevTokens++NewTokens2}),
            %adjust_level(IO, Prompt0, PrevTokens++NewTokens2, PrevLevel, NextLine2);
            adjust_level(IO, Prompt0, PrevTokens++NewTokens2, 0, NextLine2);
        {eof, NextLine} ->
            io:format("PrevTokens ~p~n", [PrevTokens]),
            {eof, PrevTokens, NextLine, []};
        {error, terminated} ->
            io:format("PrevTokens ~p~n", [PrevTokens]),
            {eof, PrevTokens, Line, []};
        Error ->
            io:format(
                      "Error! sss ~p, ~p, ~p ~n",[Error, PrevTokens, PrevLevel]),
            Error
    end.
from_string(String) ->
    from_string(String, 0).

from_string_rest(IO, Line, Rest, Acc) ->
    case read(IO, [], Line, Rest, 0) of
        {ok, Acc2, NewLine, []} ->
            io:format("from_string_rest ~p -> ~n ~p~n", [Rest, Acc2]),
            {ok, Acc ++ Acc2, NewLine};
        {ok, Acc2, NewLine, Rest2} ->
            %%from_string_rest(IO, Line, Rest2, Acc++Acc2);
            from_string_rest(IO, NewLine, Rest2, Acc++Acc2);
        {eof, Acc2, Line2, []} ->
            {eof, Acc2, Line2};
        _ ->
            {ok, Acc, Line}
    end.

remove_nl(Tokens) ->    
    lists:filter(fun({'\n', _}) -> 
                         false;
                    (_) -> true 
                 end, Tokens).

from_string(String, Line) ->
%%    io:format(standard_error, "~p~n", [length(erlang:processes())]),
    IO = tiny_io_server:start_link(String),
    {R, Acc , NewLine} = from_string_rest(IO, Line, [], []),
    tiny_io_server:stop(IO),
%%    io:format(standard_error, "~p~n", [length(erlang:processes())]),
    {R, remove_nl(Acc), NewLine}.
            

reads(IO, File, Line, PrevTokens, Acc) ->
    case read(IO, [], Line, PrevTokens, 0) of
        {ok, [], _, RestTokens}  ->
            io:format("ReadsRET: ~p~n", [{Acc, RestTokens}]),
            {ok, Acc++RestTokens};
        {ok, Tokens, NextLine, RestTokens} ->
            logger:degbug(#{reads=> Tokens}),
            R = reads(IO, File, NextLine+1, RestTokens, Acc ++ Tokens),
            {ok, element(2, R)}
    end.
file_rest(IO, Line, Acc0) ->
    case from_string_rest(IO, Line, [], []) of
        {ok, Acc, NewLine}  ->
            file_rest(IO, NewLine, Acc0++Acc);
        {eof, Acc, NewLine}  ->
            {ok, Acc0 ++ Acc, NewLine};
        Error ->
            Error
    end.
file(File, _Option) ->
    {ok, IO} = file:open(File, "r"),
    {ok, Acc, _Line} = file_rest(IO, 1, []),
    file:close(IO),
    {ok, Acc}.

-file("/usr/local/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/k-1/work/erl/elisp3/src/els_scan.erl", 553).
yystate() -> 29.

yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {13,Tlen,Ics,Line,Col};
yystate(35, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col};
yystate(34, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, [60|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, [58|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,34};
yystate(33, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(33, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(33, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(33, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {16,Tlen,Ics,Line,Col,33};
yystate(32, [40|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,32};
yystate(31, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(31, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col,31};
yystate(30, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(17, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,30};
yystate(29, [96|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [62|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [60|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [46|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [41|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [40|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [35|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(25, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(29, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,29};
yystate(28, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,28};
yystate(27, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(26, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col,27};
yystate(26, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col};
yystate(25, Ics, Line, Col, Tlen, _, _) ->
    {17,Tlen,Ics,Line,Col};
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {11,Tlen,Ics,Line,Col};
yystate(23, [64|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(23, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,23};
yystate(22, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(17, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,22};
yystate(21, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(21, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(21, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col,21};
yystate(20, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,20};
yystate(19, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,19};
yystate(18, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(26, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(18, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col,18};
yystate(17, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(17, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,17};
yystate(16, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col};
yystate(15, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col};
yystate(14, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(22, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(14, [34|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(14, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(17, Ics, Line+1, 1, Tlen+1, 15, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(17, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(17, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(17, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 93 ->
    yystate(17, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col,14};
yystate(13, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(13, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(13, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(13, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,13};
yystate(12, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,12};
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col,11};
yystate(10, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(10, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col,10};
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col};
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col};
yystate(7, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col,7};
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col};
yystate(5, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(5, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col,5};
yystate(4, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(3, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(4, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(3, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(4, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col,4};
yystate(3, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,3};
yystate(2, Ics, Line, Col, Tlen, _, _) ->
    {12,Tlen,Ics,Line,Col};
yystate(1, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,1};
yystate(0, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 69631 ->
    yystate(21, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(0, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col,0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine, TokenCol);
yyaction(1, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine, TokenCol);
yyaction(2, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine, TokenCol);
yyaction(3, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine, TokenCol);
yyaction(4, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine, TokenCol);
yyaction(5, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine, TokenCol);
yyaction(6, _, _, TokenLine, TokenCol) ->
    yyaction_6(TokenLine, TokenCol);
yyaction(7, _, _, TokenLine, TokenCol) ->
    yyaction_7(TokenLine, TokenCol);
yyaction(8, _, _, TokenLine, TokenCol) ->
    yyaction_8(TokenLine, TokenCol);
yyaction(9, _, _, TokenLine, TokenCol) ->
    yyaction_9(TokenLine, TokenCol);
yyaction(10, _, _, TokenLine, TokenCol) ->
    yyaction_10(TokenLine, TokenCol);
yyaction(11, _, _, TokenLine, TokenCol) ->
    yyaction_11(TokenLine, TokenCol);
yyaction(12, _, _, TokenLine, TokenCol) ->
    yyaction_12(TokenLine, TokenCol);
yyaction(13, _, _, TokenLine, TokenCol) ->
    yyaction_13(TokenLine, TokenCol);
yyaction(14, _, _, TokenLine, TokenCol) ->
    yyaction_14(TokenLine, TokenCol);
yyaction(15, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine, TokenCol);
yyaction(16, _, _, _, _) ->
    yyaction_16();
yyaction(17, _, _, TokenLine, TokenCol) ->
    yyaction_17(TokenLine, TokenCol);
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 20).
yyaction_0(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { integer, TokenLoc, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_1/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 22).
yyaction_1(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { float, TokenLoc, list_to_float (TokenChars) } } .

-compile({inline,yyaction_2/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 24).
yyaction_2(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { symbol, TokenLoc, TokenChars } } .

-compile({inline,yyaction_3/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 26).
yyaction_3(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { symbol, TokenLoc, TokenChars } } .

-compile({inline,yyaction_4/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 28).
yyaction_4(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { symbol, TokenLoc, TokenChars } } .

-compile({inline,yyaction_5/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 30).
yyaction_5(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { module_function, TokenLoc, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 32).
yyaction_6(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { '(', TokenLoc } } .

-compile({inline,yyaction_7/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 34).
yyaction_7(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { ')', TokenLoc } } .

-compile({inline,yyaction_8/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 36).
yyaction_8(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { '.', TokenLoc } } .

-compile({inline,yyaction_9/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 38).
yyaction_9(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { end_token, { read_macro, TokenLoc, unquote_splice } } .

-compile({inline,yyaction_10/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 40).
yyaction_10(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { end_token, { read_macro, TokenLoc, unquote } } .

-compile({inline,yyaction_11/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 42).
yyaction_11(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { end_token, { read_macro, TokenLoc, quote } } .

-compile({inline,yyaction_12/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 44).
yyaction_12(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { end_token, { read_macro, TokenLoc, backquote } } .

-compile({inline,yyaction_13/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 46).
yyaction_13(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { token, { '#(', TokenLoc } } .

-compile({inline,yyaction_14/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 48).
yyaction_14(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { end_token, { '"""', TokenLoc } } .

-compile({inline,yyaction_15/3}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 50).
yyaction_15(TokenChars, TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     [_ | String ] = lists : droplast (TokenChars),
     { token, { string, TokenLoc, String } } .

-compile({inline,yyaction_16/0}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 54).
yyaction_16() ->
     skip_token .

-compile({inline,yyaction_17/2}).
-file("/Users/k-1/work/erl/elisp3/src/els_scan.xrl", 56).
yyaction_17(TokenLine, TokenCol) ->
    TokenLoc={TokenLine,TokenCol},
     { end_token, { '\n', TokenLoc } } .
-file("/usr/local/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl", 344).
